site_name: brad
site_url: https://tcbegley.com/brad/

docs_dir: src

repo_url: https://github.com/tcbegley/brad/
edit_uri: edit/main/docs/src/

nav:
  - Home: index.md
  - User Guide:
      - Background: user-guide/index.md
      - The bootstrap: user-guide/bootstrap.md
  - API Reference: reference/index.md

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: green
    accent: light green
  font:
    text: Source Sans Pro
    code: Fira Mono
  icon:
    logo: fontawesome/solid/clone
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - codehilite:
      guess_lang: false
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search
  - mkdocstrings

extra_css:
  - static/css/custom.css
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css

extra_javascript:
  - static/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  # - static/js/highlight-js-config.js
