channels:
  - default
dependencies:
  - astropy>=4.2
  - python=3.7 # nail the python version, so conda does not try upgrading / dowgrading
  - conda-forge::ctapipe=0.10
  - conda-forge::eventio
  - conda-forge::corsikaio
  - zeromq
  - ipython
  - numba
  - numpy>=1.18
  - numpydoc
  - pytest
  - pyyaml
  - zlib
  - pip
  - h5py
  - pip:
      - pytest_runner
      - protozfits~=2.0
