[build-system]
requires      = ['poetry>=0.12']
build-backend = 'poetry.masonry.api'

[tool.metadata]
display_name  = ''
package_name  = 'limepkg-scrive'
lib_name      = 'limepkg_scrive'

[tool.poetry]
name        = 'limepkg-scrive'
version     = '1.0.13'
description = 'Scrive eSigning'
authors     = ['Scrive AB']

[[tool.poetry.source]]
name = 'lime'
url  = 'https://pypi.lime.tech/simple'

[tool.poetry.plugins.'lime_plugins']
'limepkg-scrive' = 'limepkg_scrive'

[tool.poetry.dependencies]
lime-crm = '^2.76.0'
python = '~3.7.3'

[tool.poetry.dev-dependencies]
click = '>=5.1'
autopep8 = '>=1'
flake8 = '>=2.1.0'
ipdb = '>=0.8.1'
pyreadline = '>=2.1'
pytest-watch = '>=4.1.0'
pytest = '<=5.0.1'

[tool.lime]

[tool.lime.project]
project_version = '1.26.0-poetry.20'
project_type    = 'package'

[[tool.lime.static_content]]

[tool.lime.static_content.build_step]
cwd = "frontend"
commands = ["npm ci", "npm run build"]

[tool.lime.static_content.copy_step]
source = "frontend/dist"
destination = "limepkg_scrive/web_components/static"
