[tool.poetry]
name = "kyokusui"
version = "0.1.0"
description = ""
authors = ["boke0 <speken00.tt@gmail.com>"]
license = "MIT"

include = [
    "izanami/templates/*.html",
    "izanami/templates/**/*.html",
    "izanami/static/*",
    "izanami/static/**/*",
]

[tool.poetry.dependencies]
python = "^3.9"
mitama = "^4.5.4"

[tool.poetry.dev-dependencies]
unittest = "^0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
style = "pep440"
