[tool.poetry]
name = "kcquant"
version = "0.1.4"
description = "Color quantization toolkit for exploratory data analysis of images."
authors = ["kbkus <kacikus@gmail.com>"]
repository = 'https://github.com/kbkus/kcquant'
readme = 'README.md'
keywords = ['color', 'color quantization', 'eda']

[tool.poetry.dependencies]
python = "^3.8.3"
numpy = "^1.20.1"
matplotlib = "^3.3.4"
Pillow = "^8.1.0"
sklearn = "^0.0"
imutils = "^0.5.4"
pandas = "^1.2.2"
opencv-python = "^4.5.1"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
