[tool.poetry]
name = "ocpeasy"
version = "0.1.16"
authors = ["David Barrat <david.barrat@protonmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://www.ocpeasy.org"
repository = "https://github.com/ocpeasy/ocpeasy"
documentation = "https://www.ocpeasy.org"
description = "OCPeasy is an open-source software provisioning, configuration management, and application-deployment tool enabling infrastructure as code on OpenShift."

[tool.poetry.dependencies]
python = "^3.8"
fire = "^0.3.1"
GitPython = "^3.1.12"
simple-term-menu = "^0.10.4"
PyYAML = "^5.3.1"
openshift-client = "1.0.12"
cryptography = "3.4.5"
sh = "^1.14.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
pytest = "^6.2.1"
black = "^20.8b1"
pytest-mock = "^3.5.1"
pre-commit = "^2.9.3"
coverage = "^5.3.1"
pytest-cov = "^2.10.1"
coverage-badge = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ocpeasy = "ocpeasy.__main__:cli"
