[tool.poetry]
name = "ghost-in-the-machine"
version = "0.0.6"
description = "Manage your digital presence."
authors = ["Angelo Gladding <self@angelogladding.com>"]
license = "CC-BY-4.0"
readme = "README.md"
packages = [
    { include = "ghost.py" }
]

[tool.poetry.urls]
"Homepage" = "https://angelogladding.com/code/ghost"

[tool.poetry.plugins."web.apps"]
"ghost" = "ghost:app"

[tool.poetry.dependencies]
python = "^3.9"
understory = "^0.0.1-alpha.100"

[tool.poetry.dev-dependencies]
# understory = {path = "../understory"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
