# Poetry pyproject.toml: https://python-poetry.org/docs/pyproject/

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "zettelkasten"
version = "0.2.3"
description = "CLI interface for managing a folder based zettelkasten using emacs org-mode file zettels and a bibtex reference system"
readme = "README.md"
authors = [
  "tZ3ma <mathias.ammon@tuhh.de>"
]
license = "MIT"
repository = "https://github.com/tZ3ma/zettelkasten"
homepage = "https://github.com/tZ3ma/zettelkasten"

# Keywords description https://python-poetry.org/docs/pyproject/#keywords
keywords = ['zettelkasten', 'org-mode', 'bibtex']  # Update me

# Pypi classifiers: https://pypi.org/classifiers/
classifiers = [  # Update me
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering :: Human Machine Interfaces",
]

[tool.poetry.scripts]
# Entry points for the package https://python-poetry.org/docs/pyproject/#scripts
"zettelkasten" = "zettelkasten.cli:app"

[tool.poetry.dependencies]
python = "^3.7"
importlib_metadata = {version = "^3.4.0", python = "<3.8"}
typer = {extras = ["all"], version = "^0.3.2"}
rich = "^9.13.0"

[tool.poetry.dev-dependencies]
darglint = "^1.7.0"
isort = "^5.7.0"
pyupgrade = "^2.10.0"
black = "^20.8b1"
mypy = "^0.812"
bandit = "^1.7.0"
safety = "^1.10.3"
pytest = "^6.2.1"
pylint = "^2.7.0"
pydocstyle = "^5.1.1"
pre-commit = "^2.11.0"
Sphinx = "^3.5.2"
sphinx-rtd-theme = "^0.5.1"
sphinx-paramlinks = "^0.5.0"
pytest-dependency = "^0.5.1"
smmap = "^3.0.1"
GitPython = "^3.1.14"
smmap2 = "^3.0.1"
Pygments = "^2.8.1"
importlib-metadata = "^3.7.2"
identify = "^2.1.1"

[tool.black]
# https://github.com/psf/black
line-length = 80
target-version = ["py37"]

[tool.isort]
# https://github.com/timothycrosley/isort/
known_typing = "typing,types,typing_extensions,mypy,mypy_extensions"
sections = "FUTURE,TYPING,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
include_trailing_comma = true
default_section = "FIRSTPARTY"
multi_line_output = 3
indent = 4
force_grid_wrap = 0
use_parentheses = true
line_length = 80

# pyproject.toml
